### ISSUE TITLE
Spurious tracebacks on tear down

### ISSUE THREAD

**Issue by nblock** [PyFeeds/PyFeeds#147]
The generic spider (as it seems to at first sight) causes some issue. I randomly get tracebacks during tear down:
```
Traceback (most recent call last):
  File "/home/feeds/venv/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
```

**Comment by Lukas0907** [comment]
```
2018-08-21 09:46:39 [scrapy.core.scraper] ERROR: Error downloading <GET https://gehoertgebloggt.com/feed/>
Traceback (most recent call last):
  File "/home/lukas/venvs/feeds/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
2018-08-21 09:46:39 [scrapy.core.scraper] ERROR: Error downloading <GET https://the-nerd-manager.com/feed/>
Traceback (most recent call last):
  File "/home/lukas/venvs/feeds/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
2018-08-21 09:46:46 [scrapy.core.scraper] ERROR: Error downloading <GET https://blog.cryptographyengineering.com/feed/>
Traceback (most recent call last):
  File "/home/lukas/venvs/feeds/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
```

**Comment by Lukas0907** [comment]
Increasing retries to 4 seems to be a workaround.
