### ISSUE TITLE
KeyError: 'parents'

### ISSUE THREAD

**Issue by nblock** [PyFeeds/PyFeeds#183]
I've seen this Traceback below a few times in a row for `biblioweb.at`:

```
Traceback (most recent call last):
  File "/home/feeds/venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/feeds/venv/lib/python3.7/site-packages/scrapy/core/downloader/middleware.py", line 53, in process_response
    spider=spider)
  File "/home/feeds/venv/lib/python3.7/site-packages/scrapy/downloadermiddlewares/httpcache.py", line 86, in process_response
    self._cache_response(spider, response, request, cachedresponse)
  File "/home/feeds/venv/lib/python3.7/site-packages/scrapy/downloadermiddlewares/httpcache.py", line 106, in _cache_response
    self.storage.store_response(spider, request, response)
  File "/home/feeds/feeds/feeds/cache.py", line 84, in store_response
    old_metadata["parents"] if old_metadata else []
KeyError: 'parents'
2018-10-10 05:03:31 [feeds.exporters] WARNING: Feed /home/feeds/html/biblioweb.at/feed.atom contains no items!
```

**Comment by Lukas0907** [comment]
Thanks for the report! This probably happened due to some ancient cache entries for biblioweb. Please delete the biblioweb cache and try again because I could not reproduce the problem.

**Comment by nblock** [comment]
Deleted biblioweb's cache a few days ago and this traceback no longer popped up.
