### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'

### ISSUE THREAD

**Issue by nblock** [PyFeeds/PyFeeds#206]
I see the following traceback regularly in my logs:

```
2019-07-30 18:00:13 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method CoreStats.spider_closed of <scrapy.extensions.corestats.CoreStats object at
+0x7feeb058dc18>>
Traceback (most recent call last):
  File "/home/feeds/venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/feeds/venv/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/feeds/venv/lib/python3.7/site-packages/scrapy/extensions/corestats.py", line 28, in spider_closed
    elapsed_time = finish_time - self.stats.get_value('start_time')
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
```

* Version: https://github.com/PyFeeds/PyFeeds/commit/8cdcbc1582e7b6b69497525c5e66d4251d04115b

**Comment by Lukas0907** [comment]
Reproduced. Will take a look. Thanks for the report.

**Comment by Lukas0907** [comment]
Upstream bug; see https://github.com/scrapy/scrapy/issues/4007.

Mitigation: Downgrade to older Scrapy version or setting a different stats collector.
