### ISSUE TITLE
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed

### ISSUE THREAD

**Issue by nblock** [PyFeeds/PyFeeds#230]
Fresh venv, Python 3.10.4

```
Traceback (most recent call last):
  File "/home/feeds/venv/bin/feeds", line 33, in <module>
    sys.exit(load_entry_point('PyFeeds', 'console_scripts', 'feeds')())
  File "/home/feeds/feeds/feeds/cli.py", line 137, in main
    cli(obj={})
  File "/home/feeds/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/feeds/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/feeds/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/feeds/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/feeds/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/feeds/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/feeds/feeds/feeds/cli.py", line 97, in crawl
    process.crawl(spider)
  File "/home/feeds/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 205, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/home/feeds/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 238, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/home/feeds/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 313, in _create_crawler
    return Crawler(spidercls, self.settings, init_reactor=True)
  File "/home/feeds/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 82, in __init__
    default.install()
  File "/home/feeds/venv/lib/python3.10/site-packages/twisted/internet/epollreactor.py", line 256, in install
    installReactor(p)
  File "/home/feeds/venv/lib/python3.10/site-packages/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed
```

**Comment by nblock** [comment]
No longer relevant, fixed by Scrapy 2.6+
